version: 2
jobs:
  build:
    working_directory: /go/src/github.com/31z4/harvest
    docker:
      - image: golang:1.8
    steps:
      - checkout

      - run: go get github.com/mattn/goveralls

      - run: go test -v -cover -race -coverprofile=coverage.out ./...
      - run: goveralls -coverprofile=coverage.out -service=circle-ci
